
language: java
sudo: true
branches:
  only:
  - master
jdk:
  - oraclejdk8
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
install:
    - cd /home/travis/build/Krazium/CustomJoinMessage/
    - mkdir lib
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastStableBuild/artifact/target/BuildTools.jar -P /home/travis/build/Krazium/CustomJoinMessage/lib/
script:
    - cd /home/travis/build/Krazium/CustomJoinMessage/lib/
    - java -jar BuildTools.jar --rev 1.12 > /dev/null
before_deploy:
  - "mvn -DskipTests package"
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=Build-$TRAVIS_BUILD_NUMBER
  - echo $GIT_TAG
  - git tag $GIT_TAG -a -m "CustomJoinMessage automated build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/Krazium/CustomJoinMessage --tags
  - ls -R
deploy:
  provider: releases
  api_key: $TAGPERM
  file: "target/JoinMessage.jar"
  skip_cleanup: true
  on:
    tags: false
    branch: master